set_property PACKAGE_PIN W15 [get_ports adc_driver_clk]
set_property IOSTANDARD LVCMOS33 [get_ports adc_driver_clk]
set_property IOSTANDARD LVCMOS33 [get_ports UART_1_rxd]
set_property IOSTANDARD LVCMOS33 [get_ports UART_1_txd]
set_property IOSTANDARD LVCMOS33 [get_ports {adc_datain[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {adc_datain[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {adc_datain[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {adc_datain[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {adc_datain[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {adc_datain[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {adc_datain[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {adc_datain[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {adc_datain[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {adc_datain[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {adc_datain[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {adc_datain[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {adc_datain[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {adc_datain[0]}]
set_property PACKAGE_PIN W20 [get_ports adc_pwr_en]
set_property IOSTANDARD LVCMOS33 [get_ports adc_pwr_en]
set_property PACKAGE_PIN Y6 [get_ports {adc_datain[13]}]
set_property PACKAGE_PIN W6 [get_ports {adc_datain[12]}]
set_property PACKAGE_PIN Y7 [get_ports {adc_datain[11]}]
set_property PACKAGE_PIN Y8 [get_ports {adc_datain[10]}]
set_property PACKAGE_PIN W8 [get_ports {adc_datain[9]}]
set_property PACKAGE_PIN Y9 [get_ports {adc_datain[8]}]
set_property PACKAGE_PIN W9 [get_ports {adc_datain[7]}]
set_property PACKAGE_PIN W10 [get_ports {adc_datain[6]}]
set_property PACKAGE_PIN Y11 [get_ports {adc_datain[5]}]
set_property PACKAGE_PIN W11 [get_ports {adc_datain[4]}]
set_property PACKAGE_PIN Y12 [get_ports {adc_datain[3]}]
set_property PACKAGE_PIN W13 [get_ports {adc_datain[2]}]
set_property PACKAGE_PIN Y13 [get_ports {adc_datain[1]}]
set_property PACKAGE_PIN Y14 [get_ports {adc_datain[0]}]

set_property IOSTANDARD LVCMOS33 [get_ports {GPIO_0_0_tri_io[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO_0_0_tri_io[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO_0_0_tri_io[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO_0_0_tri_io[0]}]
set_property PACKAGE_PIN A20 [get_ports {GPIO_0_0_tri_io[3]}]
set_property PACKAGE_PIN C20 [get_ports {GPIO_0_0_tri_io[1]}]
set_property PACKAGE_PIN B20 [get_ports {GPIO_0_0_tri_io[2]}]
set_property PACKAGE_PIN D20 [get_ports {GPIO_0_0_tri_io[0]}]


set_property DRIVE 12 [get_ports UART_1_txd]
set_property PULLUP true [get_ports UART_1_rxd]
set_property PULLUP true [get_ports UART_1_txd]

set_property PACKAGE_PIN U19 [get_ports UART_1_rxd]



set_property PACKAGE_PIN T20 [get_ports UART_1_txd]


set_property OFFCHIP_TERM NONE [get_ports UART_1_txd]
set_property OFFCHIP_TERM NONE [get_ports GPIO_0_0_tri_io[3]]
set_property OFFCHIP_TERM NONE [get_ports GPIO_0_0_tri_io[2]]
set_property OFFCHIP_TERM NONE [get_ports GPIO_0_0_tri_io[1]]
set_property OFFCHIP_TERM NONE [get_ports GPIO_0_0_tri_io[0]]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets clk]
